@echo off
cls
Echo Copying Icons to %HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Icons
md %HOMEDRIVE%%HOMEPATH%\Documents\DAECLI
md %HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Icons
Copy *.ico %HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Icons
Echo Generating Batch files and Copying them to %HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Batch
md %HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Batch
@ECHO OFF
for /f "delims=" %%a in ('where /R c:\users DeepArtEffectsCli.exe') do @set progpath="%%a"
REM You can change the set settings here.
set bokeh=0.0
set chunksize=0
set extension=png
set intensity=-1
set originalcolors=false
set resolution=original

echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_24a94e1e.%extension%" -resolution %resolution% -stylename "24a94e1e" >"24a94e1e.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_5b3e7a36.%extension%" -resolution %resolution% -stylename "5b3e7a36" >"5b3e7a36.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_7ece7b5a.%extension%" -resolution %resolution% -stylename "7ece7b5a" >"7ece7b5a.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_93f38fd3.%extension%" -resolution %resolution% -stylename "93f38fd3" >"93f38fd3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_98fcbb08.%extension%" -resolution %resolution% -stylename "98fcbb08" >"98fcbb08.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_a1a2bc77.%extension%" -resolution %resolution% -stylename "a1a2bc77" >"a1a2bc77.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 1.%extension%" -resolution %resolution% -stylename "abstract 1" >"abstract 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 10.%extension%" -resolution %resolution% -stylename "abstract 10" >"abstract 10.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 2.%extension%" -resolution %resolution% -stylename "abstract 2" >"abstract 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 3.%extension%" -resolution %resolution% -stylename "abstract 3" >"abstract 3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 4.%extension%" -resolution %resolution% -stylename "abstract 4" >"abstract 4.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 5.%extension%" -resolution %resolution% -stylename "abstract 5" >"abstract 5.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 6.%extension%" -resolution %resolution% -stylename "abstract 6" >"abstract 6.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 7.%extension%" -resolution %resolution% -stylename "abstract 7" >"abstract 7.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 8.%extension%" -resolution %resolution% -stylename "abstract 8" >"abstract 8.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_abstract 9.%extension%" -resolution %resolution% -stylename "abstract 9" >"abstract 9.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_alice.%extension%" -resolution %resolution% -stylename "alice" >"alice.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_anime.%extension%" -resolution %resolution% -stylename "anime" >"anime.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_aurora.%extension%" -resolution %resolution% -stylename "aurora" >"aurora.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_autumn.%extension%" -resolution %resolution% -stylename "autumn" >"autumn.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_aviator.%extension%" -resolution %resolution% -stylename "aviator" >"aviator.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_b909ea37.%extension%" -resolution %resolution% -stylename "b909ea37" >"b909ea37.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_baroque.%extension%" -resolution %resolution% -stylename "baroque" >"baroque.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_bart.%extension%" -resolution %resolution% -stylename "bart" >"bart.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_beauty.%extension%" -resolution %resolution% -stylename "beauty" >"beauty.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_bubbles.%extension%" -resolution %resolution% -stylename "bubbles" >"bubbles.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_calmness.%extension%" -resolution %resolution% -stylename "calmness" >"calmness.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_candy.%extension%" -resolution %resolution% -stylename "candy" >"candy.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_canvas.%extension%" -resolution %resolution% -stylename "canvas" >"canvas.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_capri.%extension%" -resolution %resolution% -stylename "capri" >"capri.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_caribbean.%extension%" -resolution %resolution% -stylename "caribbean" >"caribbean.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_carnival.%extension%" -resolution %resolution% -stylename "carnival" >"carnival.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_ceremony.%extension%" -resolution %resolution% -stylename "ceremony" >"ceremony.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_charles.%extension%" -resolution %resolution% -stylename "charles" >"charles.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_coffee.%extension%" -resolution %resolution% -stylename "coffee" >"coffee.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_colorful.%extension%" -resolution %resolution% -stylename "colorful" >"colorful.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_comic.%extension%" -resolution %resolution% -stylename "comic" >"comic.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_cordeville.%extension%" -resolution %resolution% -stylename "cordeville" >"cordeville.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_crinkle.%extension%" -resolution %resolution% -stylename "crinkle" >"crinkle.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_cubism.%extension%" -resolution %resolution% -stylename "cubism" >"cubism.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_dark.%extension%" -resolution %resolution% -stylename "dark" >"dark.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_dawn.%extension%" -resolution %resolution% -stylename "dawn" >"dawn.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_dd4e344b.%extension%" -resolution %resolution% -stylename "dd4e344b" >"dd4e344b.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_dd87e344.%extension%" -resolution %resolution% -stylename "dd87e344" >"dd87e344.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_discofever.%extension%" -resolution %resolution% -stylename "discofever" >"discofever.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_dotty.%extension%" -resolution %resolution% -stylename "dotty" >"dotty.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_dreamworld.%extension%" -resolution %resolution% -stylename "dreamworld" >"dreamworld.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_eagle.%extension%" -resolution %resolution% -stylename "eagle" >"eagle.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_elegant silence.%extension%" -resolution %resolution% -stylename "elegant silence" >"elegant silence.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_elisabeth.%extension%" -resolution %resolution% -stylename "elisabeth" >"elisabeth.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_epoch.%extension%" -resolution %resolution% -stylename "epoch" >"epoch.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_explosion.%extension%" -resolution %resolution% -stylename "explosion" >"explosion.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_expressionism.%extension%" -resolution %resolution% -stylename "expressionism" >"expressionism.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_eye.%extension%" -resolution %resolution% -stylename "eye" >"eye.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_fairy.%extension%" -resolution %resolution% -stylename "fairy" >"fairy.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_fantasy.%extension%" -resolution %resolution% -stylename "fantasy" >"fantasy.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_feast.%extension%" -resolution %resolution% -stylename "feast" >"feast.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_forelock.%extension%" -resolution %resolution% -stylename "forelock" >"forelock.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_forward.%extension%" -resolution %resolution% -stylename "forward" >"forward.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_gothic.%extension%" -resolution %resolution% -stylename "gothic" >"gothic.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_grace.%extension%" -resolution %resolution% -stylename "grace" >"grace.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_illustration.%extension%" -resolution %resolution% -stylename "illustration" >"illustration.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_impressionism 1.%extension%" -resolution %resolution% -stylename "impressionism 1" >"impressionism 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_impressionism 2.%extension%" -resolution %resolution% -stylename "impressionism 2" >"impressionism 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_iridescent.%extension%" -resolution %resolution% -stylename "iridescent" >"iridescent.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_joke.%extension%" -resolution %resolution% -stylename "joke" >"joke.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_landscape.%extension%" -resolution %resolution% -stylename "landscape" >"landscape.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_luminous.%extension%" -resolution %resolution% -stylename "luminous" >"luminous.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_madison.%extension%" -resolution %resolution% -stylename "madison" >"madison.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_manga.%extension%" -resolution %resolution% -stylename "manga" >"manga.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_mediterranean.%extension%" -resolution %resolution% -stylename "mediterranean" >"mediterranean.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_mixture.%extension%" -resolution %resolution% -stylename "mixture" >"mixture.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_modern art 1.%extension%" -resolution %resolution% -stylename "modern art 1" >"modern art 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_modern art 2.%extension%" -resolution %resolution% -stylename "modern art 2" >"modern art 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_modern art 3.%extension%" -resolution %resolution% -stylename "modern art 3" >"modern art 3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_modern art 4.%extension%" -resolution %resolution% -stylename "modern art 4" >"modern art 4.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_modern art 5.%extension%" -resolution %resolution% -stylename "modern art 5" >"modern art 5.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_modern art 6.%extension%" -resolution %resolution% -stylename "modern art 6" >"modern art 6.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_moonlight.%extension%" -resolution %resolution% -stylename "moonlight" >"moonlight.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_mosaic 1.%extension%" -resolution %resolution% -stylename "mosaic 1" >"mosaic 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_mosaic 2.%extension%" -resolution %resolution% -stylename "mosaic 2" >"mosaic 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_mosaic 3.%extension%" -resolution %resolution% -stylename "mosaic 3" >"mosaic 3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_mudita.%extension%" -resolution %resolution% -stylename "mudita" >"mudita.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_newspaper.%extension%" -resolution %resolution% -stylename "newspaper" >"newspaper.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_ocean.%extension%" -resolution %resolution% -stylename "ocean" >"ocean.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_oil painting.%extension%" -resolution %resolution% -stylename "oil painting" >"oil painting.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_patterns.%extension%" -resolution %resolution% -stylename "patterns" >"patterns.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pencil.%extension%" -resolution %resolution% -stylename "pencil" >"pencil.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_petals.%extension%" -resolution %resolution% -stylename "petals" >"petals.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_photography.%extension%" -resolution %resolution% -stylename "photography" >"photography.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pixel art.%extension%" -resolution %resolution% -stylename "pixel art" >"pixel art.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pointillism 1.%extension%" -resolution %resolution% -stylename "pointillism 1" >"pointillism 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pointillism 2.%extension%" -resolution %resolution% -stylename "pointillism 2" >"pointillism 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pointillism 3.%extension%" -resolution %resolution% -stylename "pointillism 3" >"pointillism 3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pop art.%extension%" -resolution %resolution% -stylename "pop art" >"pop art.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_pop.%extension%" -resolution %resolution% -stylename "pop" >"pop.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_poppy.%extension%" -resolution %resolution% -stylename "poppy" >"poppy.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_promenade.%extension%" -resolution %resolution% -stylename "promenade" >"promenade.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_retro.%extension%" -resolution %resolution% -stylename "retro" >"retro.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_satisfaction.%extension%" -resolution %resolution% -stylename "satisfaction" >"satisfaction.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_sixties.%extension%" -resolution %resolution% -stylename "sixties" >"sixties.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_sketch 1.%extension%" -resolution %resolution% -stylename "sketch 1" >"sketch 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_sketch 2.%extension%" -resolution %resolution% -stylename "sketch 2" >"sketch 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_sketch 3.%extension%" -resolution %resolution% -stylename "sketch 3" >"sketch 3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_sketchy.%extension%" -resolution %resolution% -stylename "sketchy" >"sketchy.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_snow.%extension%" -resolution %resolution% -stylename "snow" >"snow.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_summer.%extension%" -resolution %resolution% -stylename "summer" >"summer.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_sunny.%extension%" -resolution %resolution% -stylename "sunny" >"sunny.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_surrealism 1.%extension%" -resolution %resolution% -stylename "surrealism 1" >"surrealism 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_surrealism 2.%extension%" -resolution %resolution% -stylename "surrealism 2" >"surrealism 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_surrealism 3.%extension%" -resolution %resolution% -stylename "surrealism 3" >"surrealism 3.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_tears.%extension%" -resolution %resolution% -stylename "tears" >"tears.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_ukiyo-e.%extension%" -resolution %resolution% -stylename "ukiyo-e" >"ukiyo-e.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_urban.%extension%" -resolution %resolution% -stylename "urban" >"urban.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_voyage.%extension%" -resolution %resolution% -stylename "voyage" >"voyage.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_waterbird.%extension%" -resolution %resolution% -stylename "waterbird" >"waterbird.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_watercolor 1.%extension%" -resolution %resolution% -stylename "watercolor 1" >"watercolor 1.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_watercolor 2.%extension%" -resolution %resolution% -stylename "watercolor 2" >"watercolor 2.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_wolf.%extension%" -resolution %resolution% -stylename "wolf" >"wolf.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_yira.%extension%" -resolution %resolution% -stylename "yira" >"yira.bat"
echo %progpath% artfilter -bokeh %bokeh% -chunksize %chunksize% -extension %extension% -input "%%~dpnx1" -intensity %intensity% -originalcolors %originalcolors% -output " %%~dpn1_zinaida.%extension%" -resolution %resolution% -stylename "zinaida" >"zinaida.bat"
for %%a in (".\*.bat") do (
    rem check if the file has an extension and if it is not our script
    if "%%~xa" NEQ ""  if "%%~dpnxa" NEQ "%~dpnx0" (
        rem check if extension forlder exists, if not it is created
        rem Copy (or change to move) the file to directory
        move "%%a" "%HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Batch"
    )
)
Echo Generating shortcuts for Styles.
@echo off
md %HOMEDRIVE%%HOMEPATH%\Desktop\DAE-CLI
for /F "tokens=*" %%A in (styles.txt) do (
echo Set oWS = WScript.CreateObject^("WScript.Shell"^) > CreateShortcut.vbs
echo sLinkFile = "%HOMEDRIVE%%HOMEPATH%\Desktop\DAE-CLI\%%A.lnk" >> CreateShortcut.vbs
echo Set oLink = oWS.CreateShortcut^(sLinkFile^)  >> CreateShortcut.vbs
echo oLink.TargetPath = "%HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Batch\%%A.bat"  >> CreateShortcut.vbs
echo oLink.Description = "Deep Art Effects CLI v1.2.7 - Style %%A"  >> CreateShortcut.vbs
echo oLink.IconLocation = "%HOMEDRIVE%%HOMEPATH%\Documents\DAECLI\Icons\%%A.ico" >> CreateShortcut.vbs
echo oLink.WorkingDirectory = "%HOMEDRIVE%%HOMEPATH%\Desktop" >> CreateShortcut.vbs
echo oLink.Save >> CreateShortcut.vbs
cscript CreateShortcut.vbs
Echo Shortcut Created for Style - %%A in folder %HOMEDRIVE%%HOMEPATH%\Desktop\DAE-CLI
del CreateShortcut.vbs
)
cls
Echo installation complete please go to %HOMEDRIVE%%HOMEPATH%\Desktop\DAE-CLI drag a image to a shortcut to generate your desired styles.
Echo Press any key to exit this window.
Pause
